module.exports = {
    "plugins": [
        "stylelint-scss"
    ],
    "rules": {
        "at-rule-blacklist": ["extend"],
        "at-rule-empty-line-before": ["always", {
            except: [
                "blockless-after-same-name-blockless",
                "blockless-after-blockless",
                "first-nested"
            ],
            ignore: ["after-comment"],
            ignoreAtRules: ["mixin", "else"]
        }],
        "at-rule-name-case": "lower",
        "at-rule-name-newline-after": "always-multi-line",
        "at-rule-name-space-after": "always-single-line",
        "at-rule-no-vendor-prefix": true,
        "at-rule-semicolon-newline-after": "always",
        "at-rule-semicolon-space-before": "never",
        "block-closing-brace-empty-line-before": "never",
        "block-closing-brace-newline-after": ["always", {
            ignoreAtRules: ["if", "else"]
        }],
        "block-closing-brace-newline-before": "always-multi-line",
        "block-closing-brace-space-before": "always-single-line",
        "block-no-empty": true,
        "block-opening-brace-newline-after": "always-multi-line",
        "block-opening-brace-space-after": "always-single-line",
        "block-opening-brace-space-before": "always",
        "color-hex-case": "lower",
        "color-hex-length": "short",
        "color-named": ["never", {
            ignore: ["inside-function"]
        }],
        "color-no-hex": true,
        "color-no-invalid-hex": true,
        "comment-empty-line-before": [ "always", {
            except: ["first-nested"],
            ignore: ["stylelint-commands"]
        }],
        "comment-no-empty": true,
        "comment-whitespace-inside": "always",
        "comment-word-blacklist": ["/^TODO:/"],
        "custom-media-pattern": '',
        "custom-property-empty-line-before": ["always", {
            except: ["after-custom-property"]
        }],
        "declaration-bang-space-after": "never",
        "declaration-bang-space-before": "always",
        "declaration-block-no-duplicate-properties": true,
        "declaration-block-no-redundant-longhand-properties": true,
        "declaration-block-no-shorthand-property-overrides": true,
        "declaration-block-semicolon-newline-after": "always",
        "declaration-block-semicolon-newline-before": "never-multi-line",
        "declaration-block-semicolon-space-after": "always-single-line",
        "declaration-block-semicolon-space-before": "never",
        "declaration-block-single-line-max-declarations": 1,
        "declaration-block-trailing-semicolon": "always",
        "declaration-colon-newline-after": "always-multi-line",
        "declaration-colon-space-after": "always-single-line",
        "declaration-colon-space-before": "never",
        "declaration-empty-line-before": ["always", {
            except: ["after-comment", "after-declaration", "first-nested"]
        }],
        "declaration-no-important": true,
        "declaration-property-unit-blacklist": {
            "/^animation/": ["s"]
        },
        "declaration-property-unit-whitelist": {},
        "declaration-property-value-blacklist": {},
        "declaration-property-value-whitelist": {
            "background-color": ["/get-color/"],
            "border-color": ["/get-color/"],
            "color": ["/get-color/"]
        },
        "font-family-name-quotes": "always-where-recommended",
        "font-family-no-duplicate-names": true,
        "font-weight-notation": "numeric",
        "function-calc-no-unspaced-operator": true,
        "function-comma-newline-after": "always-multi-line",
        "function-comma-space-after": "always-single-line",
        "function-comma-space-before": "never",
        "function-linear-gradient-no-nonstandard-direction": true,
        "function-max-empty-lines": 0,
        "function-name-case": "lower",
        "function-parentheses-newline-inside": "always-multi-line",
        "function-parentheses-space-inside": "never-single-line",
        "function-url-no-scheme-relative": true,
        "function-url-quotes": ["always", {
            except: ["empty"]
        }],
        "function-url-scheme-blacklist": ["data:"],
        "function-whitespace-after": "always",
        "indentation": 4,
        "keyframe-declaration-no-important": true,
        "length-zero-no-unit": true,
        "max-empty-lines": 3,
        "max-nesting-depth": [2, {
            ignore: ["blockless-at-rules"]
        }],
        "media-feature-colon-space-after": "always",
        "media-feature-colon-space-before": "never",
        "media-feature-name-case": "lower",
        "media-feature-name-no-unknown": true,
        "media-feature-name-no-vendor-prefix": true,
        "media-feature-parentheses-space-inside": "never",
        "media-feature-range-operator-space-after": "always",
        "media-feature-range-operator-space-before": "always",
        "media-query-list-comma-newline-after": "never-multi-line",
        "media-query-list-comma-newline-before": "never-multi-line",
        "media-query-list-comma-space-after": "always",
        "media-query-list-comma-space-before": "never",
        "no-descending-specificity": true,
        "no-duplicate-selectors": true,
        "no-empty-source": true,
        "no-eol-whitespace": true,
        "no-extra-semicolons": true,
        "no-invalid-double-slash-comments": true,
        "no-missing-end-of-source-newline": true,
        "no-unknown-animations": true,
        "number-leading-zero": "always",
        "number-max-precision": 3,
        "number-no-trailing-zeros": true,
        "property-case": "lower",
        "property-no-unknown": [true, {
            ignoreProperties: ['text-decoration-skip-ink']
        }],
        "property-no-vendor-prefix": true,
        "rule-empty-line-before": ["always-multi-line", {
            except: ["first-nested"],
            ignore: ["after-comment"]
        }],
        "selector-attribute-brackets-space-inside": "never",
        "selector-attribute-operator-space-after": "never",
        "selector-attribute-operator-space-before": "never",
        "selector-attribute-quotes": "always",
        "selector-combinator-space-after": "always",
        "selector-combinator-space-before": "always",
        "selector-descendant-combinator-no-non-space": true,
        "selector-list-comma-newline-after": "always",
        "selector-list-comma-newline-before": "never-multi-line",
        "selector-list-comma-space-after": "always-single-line",
        "selector-list-comma-space-before": "always-single-line",
        "selector-max-attribute": 0,
        "selector-max-compound-selectors": 2,
        "selector-max-combinators": 1,
        "selector-max-empty-lines": 0,
        "selector-max-id": 0,
        "selector-max-type": 0,
        "selector-max-universal": 0,
        "selector-no-qualifying-type": true,
        "selector-no-vendor-prefix": true,
        "selector-pseudo-class-case": "lower",
        "selector-pseudo-class-no-unknown": true,
        "selector-pseudo-class-parentheses-space-inside": "never",
        "selector-pseudo-element-case": "lower",
        "selector-pseudo-element-colon-notation": "double",
        "selector-pseudo-element-no-unknown": true,
        "selector-type-case": "lower",
        "selector-type-no-unknown": true,
        "shorthand-property-no-redundant-values": true,
        "string-quotes": "double",
        "time-min-milliseconds": 100,
        "unit-case": "lower",
        "unit-no-unknown": true,
        "value-keyword-case": "lower",
        "value-list-comma-newline-after": "always-multi-line",
        "value-list-comma-newline-before": "never-multi-line",
        "value-list-comma-space-after": "always-single-line",
        "value-list-comma-space-before": "never",
        "value-list-max-empty-lines": 0,
        "value-no-vendor-prefix": true,
        "scss/at-else-closing-brace-newline-after": "always-last-in-chain",
        "scss/at-if-closing-brace-newline-after": "always-last-in-chain",
        "scss/at-import-no-partial-leading-underscore": true,
        "scss/at-mixin-argumentless-call-parentheses": "never",
        "scss/at-rule-no-unknown": true,
        "scss/dollar-variable-colon-space-after": "always-single-line",
        "scss/dollar-variable-colon-space-before": "never",
        "scss/double-slash-comment-whitespace-inside": "always",
        "scss/declaration-nested-properties-no-divided-groups": true,
        "scss/operator-no-newline-before": true,
        "scss/operator-no-unspaced": true,
        "scss/selector-no-redundant-nesting-selector": true
    }
};
